package api

import (
	"github.com/yusefnapora/party-line/audio"
	"time"
)

type InputDeviceList struct {
	Devices []audio.InputDeviceInfo
}

type UserInfo struct {
	PeerID string
	Nickname string
}

type Message struct {
	Author      UserInfo
	SentAtTime  time.Time
	TextContent string
	Attachments []MessageAttachment
}

const (
	AttachmentTypeAudioOpus = "audio/opus"
)

type MessageAttachment struct {
	Type    string
	Content []byte
}


type BeginAudioRecordingRequest struct {
	// MaxDuration is a time.ParseDuration compatible string that limits the recording to the given
	// duration. If unset, there is no max, and the recording must be stopped manually with a
	// StopAudioRecordingRequest
	MaxDuration string
}

type GenericResponse struct {
	// Error is non-empty if something failed.
	Error string
}

type BeginAudioRecordingResponse struct {
	GenericResponse

	// RecordingID is a unique ID generated by the server to identify the recording.
	// A non-empty ID indicates that the request was successful and the recording has begun.
	RecordingID string
}

type StopAudioRecordingRequest struct {
	// RecordingID is a unique ID generated by the server to identify the recording.
	RecordingID string
}

type PlayAudioRecordingRequest struct {
	RecordingID string
}